version: "3"
services:
  # https://hub.docker.com/_/mongo/
  mongo:
    container_name: dc-mongo
    env_file:
      - mongo.env
    image: mongo:latest
    networks:
      - mongo
    ports:
      - 27017:27017
    restart: always
    tty: true
    volumes:
      - ./mongo-home:/home/mongodb
      - ./mongo-db:/data/db
      - ./mongo-initdb.d:/docker-entrypoint-initdb.d
  # https://hub.docker.com/_/mongo-express/
  mongo-express:
    container_name: dc-mongodb-express
    depends_on:
      - mongo
    env_file:
      - mongo-express.env
    image: mongo-express:latest
    links:
      - mongo
    networks:
      - mongo
    ports:
      - 8081:8081
    restart: always
    tty: true

networks:
  mongo:
    driver: bridge
